### ISSUE TITLE
User session is ending too quickly

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-backend-gsa#47] opened 2022-08-03 18:57 UTC
Extend user session length.  

Additional features for production version:
- Provide user with a warning when time is running out, ask if they want to stay logged in
- If user submits an entry after they've been logged out, error message should say something like "Submission failed, user was not logged in. Please [login](https://gsa.tst.glygen.org/login) to your GSA account."

**Comment by ReneRanzinger** [comment] 2022-08-03 19:38
Duplicate of #35 . But I will close the other one.

**Comment by rykahsay** [comment] 2022-08-05 10:12
session time is set to one day now, let's try to do the rest of on the next version.

**Comment by kmartinez834** [comment] 2022-08-12 15:39
Added #50 ticket for remaining items

**Closed** 2022-08-12 16:49 UTC
Labels: resolved
